import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';

export const generateImage = async (prompt: string): Promise<string> => {
  if (!apiKey) {
      throw new Error("API_KEY is missing. Please check your environment.");
  }

  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }],
      },
    });

    if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
                const mimeType = part.inlineData.mimeType || 'image/png';
                return `data:${mimeType};base64,${part.inlineData.data}`;
            }
        }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error('Image generation failed:', error);
    throw new Error('Image generation failed. Please try a different prompt.');
  }
};